name: Github Packages
on:
  workflow_dispatch:
jobs:
  manual:
    name: npm install in examples/sample-basic 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.17.x
          registry-url: 'https://npm.pkg.github.com'
      - run: npm install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ./examples/sample-basic  
       
