name: PR Compliance

on:
  pull_request_target:
    types: [opened, edited, reopened]

# Action should have write permission to make updates to PR
permissions:
  pull-requests: write

jobs:
  pr-compliance:
    runs-on: ubuntu-latest
    steps:
      - uses: mtfoley/pr-compliance-action@main
        with:
          title-check-enable: false
          body-auto-close: false
          body-comment: false
          # all inputs are optional
          watch-files: |
            package.json
            .env.example
            Dockerfile
            .nvmrc
            tsconfig.json
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_CH_BACKEND }}
        uses: Ilshidur/action-discord@master
        with:
          args: '@{{EVENT_PAYLOAD.pull_request.user.login}} mandou uma nova PR! [{{ EVENT_PAYLOAD.pull_request.title }}]({{ EVENT_PAYLOAD.pull_request.url }}).'
