name: reviewdog
on:
  pull_request:
    types: [synchronize, opened]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ^16.13.2
          npm_version: ^8.1.2

      - name: Install dependencies
        run: npm install

      - name: review PR
        uses: reviewdog/action-eslint@v1
        with:
          reporter: github-pr-review
